export default {
    GET_PERMISSION: "GET_PERMISSION",
    GET_PERMISSION_FULFILLED: "GET_PERMISSION_FULFILLED",
    GET_PERMISSIONS: "GET_PERMISSIONS",
    GET_PERMISSIONS_FULFILLED: "GET_PERMISSIONS_FULFILLED",
    STORE_PERMISSION: "STORE_PERMISSION",
    STORE_PERMISSION_FULFILLED: "STORE_PERMISSION_FULFILLED",
    DELETE_PERMISSION: "DELETE_PERMISSION",
    DELETE_PERMISSION_FULFILLED: "DELETE_PERMISSION_FULFILLED",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    UPDATE_PERMISSION_FULFILLED: "UPDATE_PERMISSION_FULFILLED",
};
