export default {
    GET_ADMINS:'GET_ADMINS',
    GET_ADMINS_FULFILLED:'GET_ADMINS_FULFILLED',
    STORE_ADMIN:'STORE_ADMIN',
    STORE_ADMIN_FULFILLED:'STORE_ADMIN_FULFILLED',
    GET_ADMIN:'GET_ADMIN',
    GET_ADMIN_FULFILLED:'GET_ADMIN_FULFILLED',
    DELETE_ADMIN:'DELETE_ADMIN',
    DELETE_ADMIN_FULFILLED:'DELETE_ADMIN_FULFILLED',
    UPDATE_ADMIN:'UPDATE_ADMIN',
    UPDATE_ADMIN_FULFILLED:'UPDATE_ADMIN_FULFILLED',
}