export default {
    GET_SERVICE: "GET_SERVICE",
    GET_SERVICE_FULFILLED: "GET_SERVICE_FULFILLED",
    STORE_SERVICE: "STORE_SERVICE",
    STORE_SERVICE_FULFILLED: "STORE_SERVICE_FULFILLED",
    GET_SERVICE: "GET_SERVICE",
    GET_SERVICE_FULFILLED: "GET_SERVICE_FULFILLED",
    DELETE_SERVICE: "DELETE_SERVICE",
    DELETE_SERVICE_FULFILLED: "DELETE_SERVICE_FULFILLED",
    UPDATE_SERVICE: "UPDATE_SERVICE",
    UPDATE_SERVICE_FULFILLED: "UPDATE_SERVICE_FULFILLED",
};
